-- MySQL Script generated by MySQL Workbench
-- 05/22/14 15:44:28
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ogcedi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ogcedi` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ogcedi` ;

-- -----------------------------------------------------
-- Table `ogcedi`.`Formation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ogcedi`.`Formation` ;

CREATE TABLE IF NOT EXISTS `ogcedi`.`Formation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogcedi`.`Promotion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ogcedi`.`Promotion` ;

CREATE TABLE IF NOT EXISTS `ogcedi`.`Promotion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `Formation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Promotion_Formation_idx` (`Formation_id` ASC),
  CONSTRAINT `fk_Promotion_Formation`
    FOREIGN KEY (`Formation_id`)
    REFERENCES `ogcedi`.`Formation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogcedi`.`UV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ogcedi`.`UV` ;

CREATE TABLE IF NOT EXISTS `ogcedi`.`UV` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `Promotion_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_UV_Promotion1_idx` (`Promotion_id` ASC),
  CONSTRAINT `fk_UV_Promotion1`
    FOREIGN KEY (`Promotion_id`)
    REFERENCES `ogcedi`.`Promotion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogcedi`.`Departement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ogcedi`.`Departement` ;

CREATE TABLE IF NOT EXISTS `ogcedi`.`Departement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogcedi`.`Module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ogcedi`.`Module` ;

CREATE TABLE IF NOT EXISTS `ogcedi`.`Module` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `information` TEXT NULL,
  `UV_id` INT NOT NULL,
  `Departement_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Module_UV1_idx` (`UV_id` ASC),
  INDEX `fk_Module_Departement1_idx` (`Departement_id` ASC),
  CONSTRAINT `fk_Module_UV1`
    FOREIGN KEY (`UV_id`)
    REFERENCES `ogcedi`.`UV` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Module_Departement1`
    FOREIGN KEY (`Departement_id`)
    REFERENCES `ogcedi`.`Departement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogcedi`.`TypeActivite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ogcedi`.`TypeActivite` ;

CREATE TABLE IF NOT EXISTS `ogcedi`.`TypeActivite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogcedi`.`Personne`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ogcedi`.`Personne` ;

CREATE TABLE IF NOT EXISTS `ogcedi`.`Personne` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogcedi`.`Intervenant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ogcedi`.`Intervenant` ;

CREATE TABLE IF NOT EXISTS `ogcedi`.`Intervenant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `enseignant` TINYINT(1) NULL,
  `thesard` TINYINT(1) NULL,
  `etablissement` VARCHAR(45) NULL,
  `Departement_id` INT NOT NULL,
  `Personne_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Intervenant_Departement1_idx` (`Departement_id` ASC),
  INDEX `fk_Intervenant_Personne1_idx` (`Personne_id` ASC),
  CONSTRAINT `fk_Intervenant_Departement1`
    FOREIGN KEY (`Departement_id`)
    REFERENCES `ogcedi`.`Departement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Intervenant_Personne1`
    FOREIGN KEY (`Personne_id`)
    REFERENCES `ogcedi`.`Personne` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogcedi`.`Activite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ogcedi`.`Activite` ;

CREATE TABLE IF NOT EXISTS `ogcedi`.`Activite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `charge` INT NULL,
  `nombre` INT NULL,
  `information` TEXT NULL,
  `TypeActivite_id` INT NOT NULL,
  `Intervenant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Activite_TypeActivite1_idx` (`TypeActivite_id` ASC),
  INDEX `fk_Activite_Intervenant1_idx` (`Intervenant_id` ASC),
  CONSTRAINT `fk_Activite_TypeActivite1`
    FOREIGN KEY (`TypeActivite_id`)
    REFERENCES `ogcedi`.`TypeActivite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Activite_Intervenant1`
    FOREIGN KEY (`Intervenant_id`)
    REFERENCES `ogcedi`.`Intervenant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogcedi`.`ActiviteModule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ogcedi`.`ActiviteModule` ;

CREATE TABLE IF NOT EXISTS `ogcedi`.`ActiviteModule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Module_id` INT NOT NULL,
  `Activite_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ActiviteModule_Module1_idx` (`Module_id` ASC),
  INDEX `fk_ActiviteModule_Activite1_idx` (`Activite_id` ASC),
  CONSTRAINT `fk_ActiviteModule_Module1`
    FOREIGN KEY (`Module_id`)
    REFERENCES `ogcedi`.`Module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActiviteModule_Activite1`
    FOREIGN KEY (`Activite_id`)
    REFERENCES `ogcedi`.`Activite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogcedi`.`Utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ogcedi`.`Utilisateur` ;

CREATE TABLE IF NOT EXISTS `ogcedi`.`Utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `admin` TINYINT(1) NULL,
  `Personne_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Utilisateur_Personne1_idx` (`Personne_id` ASC),
  CONSTRAINT `fk_Utilisateur_Personne1`
    FOREIGN KEY (`Personne_id`)
    REFERENCES `ogcedi`.`Personne` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
